### PR TITLE
pandas DataFrame.from_items deprecated >>from_records

### PR DESCRIPTION
**Pull request by KalinNonchev**

### CODE REVIEW

**Comment by KalinNonchev** [comment]
https://pandas.pydata.org/pandas-docs/version/0.23.4/generated/pandas.DataFrame.from_items.html

**Comment by Avsecz** [comment]
Thanks!

**Comment by Avsecz** [comment]
I'll make a release to pypi soon.

**Comment by KalinNonchev** [comment]
Ok, let me know

**Pull request merged**
